name: my_archery
description: "Train more efficiently with My Archery."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_rating_stars: ^1.1.0
  url_launcher: ^6.3.0
  shared_preferences: ^2.3.2
  package_info_plus: ^8.0.2
  flutter_colorpicker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.webp"
  min_sdk_android: 21
